# Generated by Django 5.0.7 on 2024-07-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post', verbose_name='Пост'),
            preserve_default=False,
        ),
    ]
